// <auto-generated />
using System;
using FitwomanAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitwomanAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722203954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitwomanAPI.Models.Categoria", b =>
                {
                    b.Property<long>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Clase", b =>
                {
                    b.Property<long>("IdClases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_clases");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdClases"));

                    b.Property<int>("Cupos")
                        .HasColumnType("integer")
                        .HasColumnName("cupos");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripción");

                    b.Property<int>("Duracion")
                        .HasColumnType("integer")
                        .HasColumnName("duración");

                    b.Property<long>("IdProfesor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_profesor");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("IdClases");

                    b.HasIndex("IdProfesor");

                    b.ToTable("clases");
                });

            modelBuilder.Entity("FitwomanAPI.Models.ClaseHorario", b =>
                {
                    b.Property<long>("IdClases")
                        .HasColumnType("bigint")
                        .HasColumnName("id_clases");

                    b.Property<long>("IdHorarios")
                        .HasColumnType("bigint")
                        .HasColumnName("id_horarios");

                    b.Property<string>("Aula")
                        .HasColumnType("text")
                        .HasColumnName("aula");

                    b.HasKey("IdClases", "IdHorarios");

                    b.HasIndex("IdHorarios");

                    b.ToTable("clases_horarios");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Contacto", b =>
                {
                    b.Property<long>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_contacto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdContacto"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Correo")
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("dirección");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("teléfono");

                    b.Property<string>("UrlGoogleMaps")
                        .HasColumnType("text")
                        .HasColumnName("url_google_maps");

                    b.HasKey("IdContacto");

                    b.ToTable("contacto");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Horario", b =>
                {
                    b.Property<long>("IdHorarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_horarios");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdHorarios"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia_semana");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.HasKey("IdHorarios");

                    b.ToTable("horarios");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Miembro", b =>
                {
                    b.Property<long>("IdMiembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_miembro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdMiembro"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<long?>("Plan")
                        .HasColumnType("bigint")
                        .HasColumnName("plan");

                    b.HasKey("IdMiembro");

                    b.ToTable("miembro");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Notificacion", b =>
                {
                    b.Property<long>("IdNotificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_notificaciones");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdNotificaciones"));

                    b.Property<string>("EnlaceReferencia")
                        .HasColumnType("text")
                        .HasColumnName("enlace_referencia");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<bool>("Tipo")
                        .HasColumnType("boolean")
                        .HasColumnName("tipo");

                    b.HasKey("IdNotificaciones");

                    b.ToTable("notificaciones");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Pago", b =>
                {
                    b.Property<long>("IdPagos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_pagos");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPagos"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<long>("IdMiembro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_miembro");

                    b.Property<string>("MesFacturado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mes_facturado");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.HasKey("IdPagos");

                    b.HasIndex("IdMiembro");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Plan", b =>
                {
                    b.Property<int>("IdPlanes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_planes");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanes"));

                    b.Property<bool>("Destacado")
                        .HasColumnType("boolean")
                        .HasColumnName("destacado");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("ItemsIncluidos")
                        .HasColumnType("jsonb")
                        .HasColumnName("items_incluidos");

                    b.Property<string>("MensajeWhatsapp")
                        .HasColumnType("text")
                        .HasColumnName("mensaje_whatsapp");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision")
                        .HasColumnName("precio");

                    b.HasKey("IdPlanes");

                    b.ToTable("planes");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Producto", b =>
                {
                    b.Property<long>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProducto"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdCategoria")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Imagen")
                        .HasColumnType("text")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<string>("Tallas")
                        .HasColumnType("text")
                        .HasColumnName("tallas");

                    b.Property<bool>("Visibilidad")
                        .HasColumnType("boolean")
                        .HasColumnName("visibilidad");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Profesor", b =>
                {
                    b.Property<long>("IdProfesores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_profesores");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProfesores"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdProfesores");

                    b.ToTable("profesores");
                });

            modelBuilder.Entity("FitwomanAPI.Models.RegistroPeso", b =>
                {
                    b.Property<long>("IdRegistroPesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_registro_pesos");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdRegistroPesos"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdMiembro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_miembro");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.HasKey("IdRegistroPesos");

                    b.HasIndex("IdMiembro");

                    b.ToTable("registro_pesos");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuarios");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUsuarios"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contraseña");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuarios");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Clase", b =>
                {
                    b.HasOne("FitwomanAPI.Models.Profesor", "Profesor")
                        .WithMany("Clases")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("FitwomanAPI.Models.ClaseHorario", b =>
                {
                    b.HasOne("FitwomanAPI.Models.Clase", "Clase")
                        .WithMany("ClasesHorarios")
                        .HasForeignKey("IdClases")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitwomanAPI.Models.Horario", "Horario")
                        .WithMany("ClasesHorarios")
                        .HasForeignKey("IdHorarios")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Pago", b =>
                {
                    b.HasOne("FitwomanAPI.Models.Miembro", "Miembro")
                        .WithMany("Pagos")
                        .HasForeignKey("IdMiembro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Producto", b =>
                {
                    b.HasOne("FitwomanAPI.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FitwomanAPI.Models.RegistroPeso", b =>
                {
                    b.HasOne("FitwomanAPI.Models.Miembro", "Miembro")
                        .WithMany("RegistrosPesos")
                        .HasForeignKey("IdMiembro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Clase", b =>
                {
                    b.Navigation("ClasesHorarios");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Horario", b =>
                {
                    b.Navigation("ClasesHorarios");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Miembro", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("RegistrosPesos");
                });

            modelBuilder.Entity("FitwomanAPI.Models.Profesor", b =>
                {
                    b.Navigation("Clases");
                });
#pragma warning restore 612, 618
        }
    }
}
